Config = {
    keybind = "R",
    reviveMessage = "Premi [%s] per creare un clone",
    noclipBind = "F10",
    healthTreshold = 0, -- How many hp do you need to have to be considered dead

    clientEvent = "br_shadowClone:playerRevived",
    serverEvent = "br_shadowClone:playerRevived",
}

Keys = {
    ["A"] = { name = "~INPUT_VEH_HYDRAULICS_CONTROL_LEFT~", index = 338 },
    ["B"] = { name = "~INPUT_REPLAY_STARTPOINT~", index = 305 },
    ["C"] = { name = "~INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP~", index = 324 },
    ["D"] = { name = "~INPUT_VEH_HYDRAULICS_CONTROL_UD~", index = 342 },
    ["E"] = { name = "~INPUT_VEH_FLY_COUNTER~", index = 356 },
    ["F"] = { name = "~INPUT_CREATOR_RS~", index = 251 },
    ["G"] = { name = "~INPUT_CELLPHONE_CAMERA_GRID~", index = 183 },
    ["H"] = { name = "~INPUT_REPLAY_HIDEHUD~", index = 304 },
    -- ["I"] = {},
    -- ["J"] = {},
    ["K"] = { name = "~INPUT_REPLAY_SHOWHOTKEY~", index = 311 },
    ["L"] = { name = "~INPUT_CELLPHONE_CAMERA_FOCUS_LOCK~", index = 182 },
    ["M"] = { name = "~INPUT_REPLAY_NEWMARKER~", index = 301 },
    ["N"] = { name = "~INPUT_REPLAY_ENDPOINT~", index = 306 },
    -- ["O"] = {},
    ["P"] = { name = "~INPUT_FRONTEND_PAUSE~", index = 199 },
    ["Q"] = { name = "~INPUT_MELEE_ATTACK2~", index = 264 },
    ["R"] = { name = "~INPUT_RELOAD~", index = 45 },
    ["S"] = { name = "~INPUT_REPLAY_RECORD~", index = 302 },
    ["T"] = { name = "~INPUT_REPLAY_TOOLS~", index = 309 },
    ["U"] = { name = "~INPUT_REPLAY_SCREENSHOT~", index = 303 },
    ["V"] = { name = "~INPUT_REPLAY_TIMELINE_PLACE_CLIP~", index = 325 },
    ["W"] = { name = "~INPUT_SCRIPT_PAD_UP~", index = 232 },
    ["X"] = { name = "~INPUT_VEH_TRANSFORM~", index = 357 },
    ["Y"] = { name = "~INPUT_MP_TEXT_CHAT_TEAM~", index = 246 },
    ["Z"] = { name = "~INPUT_HUD_SPECIAL~", index = 48 },

    ["1"] = { name = "~INPUT_SELECT_WEAPON_UNARMED~", index = 157 },
    ["2"] = { name = "~INPUT_SELECT_WEAPON_MELEE~", index = 158 },
    ["3"] = { name = "~INPUT_SELECT_WEAPON_SHOTGUN~", index = 160 },
    ["4"] = { name = "~INPUT_SELECT_WEAPON_HEAVY~", index = 164 },
    ["5"] = { name = "~INPUT_SELECT_WEAPON_SPECIAL~", index = 165 },
    ["6"] = { name = "~INPUT_SELECT_WEAPON_HANDGUN~", index = 159 },
    ["7"] = { name = "~INPUT_SELECT_WEAPON_SMG~", index = 161 },
    ["8"] = { name = "~INPUT_SELECT_WEAPON_AUTO_RIFLE~", index = 162 },
    ["9"] = { name = "~INPUT_SELECT_WEAPON_SNIPER~", index = 163 },

    ["F1"] = { name = "~INPUT_REPLAY_START_STOP_RECORDING~", index = 288 },
    ["F2"] = { name = "~INPUT_REPLAY_START_STOP_RECORDING_SECONDARY~", index = 289 },
    ["F3"] = { name = "~INPUT_SAVE_REPLAY_CLIP~", index = 170 },
    ["F5"] = { name = "~INPUT_REPLAY_TIMELINE_SAVE~", index = 327 },
    ["F6"] = { name = "~INPUT_SELECT_CHARACTER_FRANKLIN~", index = 167 },
    ["F7"] = { name = "~INPUT_SELECT_CHARACTER_TREVOR~", index = 168 },
    ["F8"] = { name = "~INPUT_SELECT_CHARACTER_MULTIPLAYER~", index = 169 },
    ["F9"] = { name = "~INPUT_DROP_WEAPON~", index = 56 },
    ["F10"] = { name = "~INPUT_DROP_AMMO~", index = 57 },
    ["F11"] = { name = "~INPUT_SWITCH_VISOR~", index = 344 },

    ["ARROWUP"] = { name = "~INPUT_CELLPHONE_UP~", index = 172 },
    ["ARROWDOWN"] = { name = "~INPUT_CELLPHONE_DOWN~", index = 173 },
    ["ARROWLEFT"] = { name = "~INPUT_CELLPHONE_LEFT~", index = 174 },
    ["ARROWRIGHT"] = { name = "~INPUT_CELLPHONE_RIGHT~", index = 175},

    ["SCROLLWHEELBUTTON"] = { name = "~INPUT_MAP_POI~", index = 348 },
    ["SCROLLWHEELDOWN"] = { name = "~INPUT_VEH_SLOWMO_DOWN_ONLY~", index = 336 },
    ["SCROLLWHEELUP"] = { name = "~INPUT_VEH_SLOWMO_UP_ONLY~", index = 335 },

    ["SPACEBAR"] = { name = "~INPUT_VEH_PARACHUTE~", index = 353 },
    ["ENTER"] = { name = "~INPUT_FRONTEND_ENDSCREEN_ACCEPT~", index = 215 },
    ["DELETE"] = { name = "~INPUT_REPLAY_CLIP_DELETE~", index = 297 },
    ["BACKSPACE"] = { name = "~INPUT_FRONTEND_RRIGHT~", index = 194 },
    ["INSERT"] = { name = "~INPUT_VEH_FLY_ATTACK_CAMERA~", index = 121 },
    ["CAPSLOCK"] = { name = "~INPUT_FRONTEND_SELECT~", index = 217 },
    ["ESC"] = { name = "~INPUT_REPLAY_TOGGLE_TIMELINE~", index = 322 },
    ["HOME"] = { name = "~INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY~", index = 213 },
    ["LEFT CONTROL"] = { name = "~INPUT_FRONTEND_RS~", index = 210 },
    ["LEFT ALT"] = { name = "~INPUT_CHARACTER_WHEEL~", index = 19 },
    ["LEFT SHIFT"] = { name = "~INPUT_VEH_FLY_BOOST~", index = 352 },
    ["LEFTMOUSEBUTTON"] = { name = "~INPUT_VEH_MELEE_LEFT~", index = 346 },
    ["RIGHTMOUSEBUTTON"] = { name = "~INPUT_VEH_MELEE_RIGHT~", index = 347 },
    ["LEFT CTRL"] = { name = "~INPUT_VEH_HYDRAULICS_CONTROL_LR~", index = 343 },
    ["TAB"] = { name = "~INPUT_REPLAY_SNAPMATIC_PHOTO~", index = 349 },
    ["["] = { name = "~INPUT_REPLAY_CYCLEMARKERLEFT~", index = 312 },
    ["]"] = { name = "~INPUT_REPLAY_CYCLEMARKERRIGHT~", index = 313 },
    ["."] = { name = "~INPUT_VEH_NEXT_RADIO~", index = 81 },
    [","] = { name = "~INPUT_VEH_PREV_RADIO~", index = 82 },
    ["= "] = { name = "~INPUT_VEH_NEXT_RADIO_TRACK~", index = 83 },
    ["-"] = { name = "~INPUT_VEH_PREV_RADIO_TRACK~", index = 84 },

    ["NUMPAD 4"] = { name = "~INPUT_VEH_SUB_TURN_LEFT_ONLY~", index = 124 },
    ["NUMPAD 5"] = { name = "~INPUT_VEH_SUB_PITCH_DOWN_ONLY~", index = 128 },
    ["NUMPAD 6"] = { name = "~INPUT_VEH_SUB_TURN_RIGHT_ONLY~", index = 125 },
    ["NUMPAD 7"] = { name = "~INPUT_VEH_FLY_SELECT_TARGET_LEFT~", index = 117 },
    ["NUMPAD 8"] = { name = "~INPUT_VEH_SUB_PITCH_UP_ONLY~", index = 127 },
    ["NUMPAD 9"] = { name = "~INPUT_VEH_FLY_SELECT_TARGET_RIGHT~", index = 118 },
    ["NUMPAD +"] = { name = "~INPUT_REPLAY_FOVINCREASE~", index = 314 },
    ["NUMPAD -"] = { name = "~INPUT_REPLAY_FOVDECREASE~", index = 315 },
    ["PAGEUP"] = { name = "~INPUT_SCRIPTED_FLY_ZUP~", index = 10 },
    ["PAGEDOWN"] = { name = "~INPUT_SCRIPTED_FLY_ZDOWN~", index = 11 },
}